### ISSUE TITLE
Proposal: add Playwright, lower Selenium

### ISSUE THREAD

**Issue by 304NotModified** [MoienTajik/AspNetCore-Developer-Roadmap#105]
In my opinion:

[Playwright](https://playwright.dev/) should be the default E2E tool. Developed by Microsoft, RTM and available for .NET, JavaScript, Typescript and more.

**Comment by MoienTajik** [comment]
Could you send a PR for this one? Alongside `Selenium`, `Playwright` might also be an option.

**Comment by 304NotModified** [comment]
Nope sorry, i dont have (or want) xMind
