### ISSUE TITLE
Proposal: add snapshot testing

### ISSUE THREAD

**Issue by 304NotModified** [MoienTajik/AspNetCore-Developer-Roadmap#106]
For some cases snapshot testing is a lot better than asserting by hand.

Libraries:

- https://github.com/VerifyTests/Verify (1.3 million downloads on [NuGet](https://www.nuget.org/packages/Verify))
- https://github.com/SwissLife-OSS/snapshooter (1.2 million downloads on [NuGet](https://www.nuget.org/packages/Snapshooter))
- older, not maintained; https://github.com/approvals/ApprovalTests.Net (3.7 million downloads on [NuGet](https://www.nuget.org/packages/ApprovalTests))

**Comment by MoienTajik** [comment]
I'm ok with that. Could you send a PR for it please?

**Comment by 304NotModified** [comment]
Nope sorry, i dont have (or want) xMind
