### ISSUE TITLE
proposal: add test data generation

### ISSUE THREAD

**Issue by 304NotModified** [MoienTajik/AspNetCore-Developer-Roadmap#107]
libraries like:

- [Autofixture ](https://github.com/AutoFixture/AutoFixture) (in NuGet top 100!)
- [Bogus ](https://github.com/bchavez/Bogus)port of Faker.js, also deterministic data generation

**Comment by MoienTajik** [comment]
I'm ok with that. Could you send a PR for it please?

**Comment by 304NotModified** [comment]
Nope sorry, i dont have (or want) xMind
