### ISSUE TITLE
Is Quartz.NET not recommended in asp.net core for scheduling job?

### ISSUE THREAD

**Issue by WeihanLi** [MoienTajik/AspNetCore-Developer-Roadmap#12]
Is Quartz.NET not recommended in asp.net core for scheduling job? If so, can you explain the reason why 
it's not recommended?

**Comment by MoienTajik** [comment]
Yes, It's not recommended. There are a lot of better choices for job scheduling like HangFire, Fluent-Scheduler, Coravel. Quartz is too complicated than other ones and I see a lot of people that they agree with this.

**Comment by WeihanLi** [comment]
OK, Thanks for your reply.
