### ISSUE TITLE
Roadmap Image In Turkish

### ISSUE THREAD

**Issue by coderserdar** [MoienTajik/AspNetCore-Developer-Roadmap#126]
There is no image on Turkish readme file.
Because of this, we are seeing this screenshot 
![Screenshot_2](https://user-images.githubusercontent.com/11051271/222168589-c3228651-5b7f-4592-998a-7a2ccefeb8e7.png)

**Comment by Ertan222** [comment]
You are right, there is no image in repository for Turkish developer map version. Maybe still under maintainenance?

**Comment by MoienTajik** [comment]
Resolved. The image URL was incorrect. Although, other languages are not updated to 2023 version as I'm not expert at them and need community help to update them.

**Comment by coderserdar** [comment]
Thanks for your immediate action.
