### ISSUE TITLE
Update Chinese, Turkish, Japanese versions to 2023

### ISSUE THREAD

**Issue by MoienTajik** [MoienTajik/AspNetCore-Developer-Roadmap#128]
All languages except English are outdated and do not follow the 2023 version. To update them, we need the community's help.

Outdated languages:
- ~~Traditional Chinese~~
- ~~Simplified Chinese~~
- Turkish
- Japanese

**Comment by nermeennasim** [comment]
I am willing to help

**Comment by kkbruce** [comment]
[Traditional Chinese](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap/pull/132) is PR and waiting for review.

Wait for zh-Hant PR to finish. I will follow up with zh-Hans' PR.

**Comment by MoienTajik** [comment]
@kkbruce Approved. Thanks!

**Comment by kkbruce** [comment]
@MoienTajik 

[Simplified Chinese](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap/pull/135) is PR and waiting for review.

**Comment by kkbruce** [comment]
@MoienTajik  Help me review this PR https://github.com/MoienTajik/AspNetCore-Developer-Roadmap/pull/136
