### ISSUE TITLE
What about Razor Component?

### ISSUE THREAD

**Issue by iAmBipinPaul** [MoienTajik/AspNetCore-Developer-Roadmap#13]
Razor component is official now it it will ship officially with .NET Core 3.0 (ASP.NET Core 3.0)
https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/?view=aspnetcore-3.0#components

**Comment by MoienTajik** [comment]
Where do you think we can put that?

**Comment by iAmBipinPaul** [comment]
I see you have mentioned Razor pages a and MVC here in ASP.NET Core Basics 
![image](https://user-images.githubusercontent.com/9201481/53925115-e9a27e00-40a6-11e9-9be1-2dbb535e403a.png)

Not sure but may be we can have another node connected to Root node as Client side and there we can have two child 
1. Razor Component 
2. Blazor 

Like here 

We can have client side and two node connected with that (Razor Component and Blazor)

![image](https://user-images.githubusercontent.com/9201481/53925350-c3c9a900-40a7-11e9-81c0-99aeda6cbc7e.png)

**Comment by MoienTajik** [comment]
Added c355abc4a2c98bad9f691afa78366f008fa53bab
