### ISSUE TITLE
Add OpenSearch Stack near ELK stack

### ISSUE THREAD

**Issue by yaryrslv** [MoienTajik/AspNetCore-Developer-Roadmap#133]
Hi, recently **Elasticsearch** and **Kibana** became paid, but their forks are actively developing and many have already switched to them, namely **OpenSearch** and **OpenSearchDashboard**, so I propose to add OpenSearch stack next to ELK stack in:
Monitoring/Logging/Tracing/Allerting => Logging => On-Permises => **OpenSearch Stack**

**Comment by MoienTajik** [comment]
Added! Thanks. 🚀
