### ISSUE TITLE
Add a Codestyle subsection to the C# section

### ISSUE THREAD

**Issue by yaryrslv** [MoienTajik/AspNetCore-Developer-Roadmap#139]
There is a suggestion to add a **Codestyle** subsection to the C# section, for example:
**C#** => **Codestyle**

**Comment by Bardin08** [comment]
@yaryrslv, what do you mean under "Codestyle"? General naming rules, etc?

**Comment by MoienTajik** [comment]
I would like to have StyleCop as a standard format/rule here.
