### ISSUE TITLE
Create SVG or move away from XMind

### ISSUE THREAD

**Issue by keithelder** [MoienTajik/AspNetCore-Developer-Roadmap#145]
Can we get an SVG of the roadmap, or move away from xMind to create the map (since it requires a license) to export to a different format?

**Comment by MoienTajik** [comment]
Hi,
xMind offers a free version of their software that does not require a license.

**Comment by keithelder** [comment]
At work we cannot install stuff like that. I am trying to get the roadmap imported into a LucidChart but keep running into dead ends.

**Comment by MoienTajik** [comment]
Actually, I don't have any plans to move away from xMind as it perfectly supports my needs and also have free plan.
