### ISSUE TITLE
分享

### ISSUE THREAD

**Issue by liulinduke** [MoienTajik/AspNetCore-Developer-Roadmap#15]
https://www.cnblogs.com/enjoy233/p/AspNetCore_developer_roadmap.html

**Comment by MoienTajik** [comment]
Could you explain your issue in English, please?

**Comment by Wonderdch** [comment]
> Could you explain your issue in English, please?

分享 == Share, He reprinted your amazing roadmap to his blog.

**Comment by MoienTajik** [comment]
Nice! So is that an update to the existing one?

**Comment by Wonderdch** [comment]
> Nice! So is that an update to the existing one?

Same content(you have done a good job), but he provided translation of the [Resource](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap#resources).

**Comment by MoienTajik** [comment]
So again thanks for your amazing support and sharing! I close this issue as it's not really an issue.
