### ISSUE TITLE
日志框架部分 Exceptionless

### ISSUE THREAD

**Issue by flybalance** [MoienTajik/AspNetCore-Developer-Roadmap#16]
日志框架部分有个开源的项目Exceptionless，希望能加入到节点上，这样，可以用这个路线图作为知识储备的备忘

**Comment by MoienTajik** [comment]
Could you explain your issue in English, please?

**Comment by iskcal** [comment]
He said there was an open source about log frameworks called Exceptionless, which could be added into the roadmap.

**Comment by StanislavPrusac** [comment]
Suggestion: ZeroMQ
