### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by fceci90** [MoienTajik/AspNetCore-Developer-Roadmap#18]
What do you think about adding SQLite to to relational databases section? I've never used it personally, but I know it is widely used and it is something that has been on my personal "learn it" list. [SQLite Homepage](https://sqlite.org/index.html)

**Comment by MoienTajik** [comment]
SQLite has very similarities with SQL Server ( as of reading & writing queries ) and I don't think that these are very different from each other.
