### ISSUE TITLE
Add Items

### ISSUE THREAD

**Issue by Aprite** [MoienTajik/AspNetCore-Developer-Roadmap#23]
Databases
+Hadoop/Spark/Storm
+Machine Leaming/Deep Learning
MS have ML.NET 1.0
https://github.com/dotnet/machinelearning

**Comment by kingreatwill** [comment]
Flink

**Comment by MoienTajik** [comment]
Thanks for your suggestions!
I think at least machine learning and its other kinds of stuff should not be included in "ASP.NET Core Roadmap". Am I right?
