### ISSUE TITLE
Learning SQL Fundamentals before the EF core

### ISSUE THREAD

**Issue by Jurabek** [MoienTajik/AspNetCore-Developer-Roadmap#24]
Before the starting EF core, at least you should understand how SQL works and how ef core uses SQL in the low level and etc.

**Comment by MoienTajik** [comment]
This roadmap actually focused on ASP.NET Core, We've [mentioned](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap#resources) some other things like SQL Fundamentals as prerequisites.
