### ISSUE TITLE
a advice

### ISSUE THREAD

**Issue by Somnus** [MoienTajik/AspNetCore-Developer-Roadmap#25]
Maybe you can insert Job Scheduler to this roadmap.

**Comment by MoienTajik** [comment]
Thanks, I'll do that for the 2020 version of it. 👍🏻

**Comment by miladj3** [comment]
I think you should add grpc at section API Client

**Comment by yeahe83** [comment]
How about security likes authentication、authorization、identityserver4, microservice likes ocelot、cousul, even cloud native like docker、k8s，devops,  cicd?

**Comment by MoienTajik** [comment]
These changes applied in the 2021 version.
