### ISSUE TITLE
Draw.io image template

### ISSUE THREAD

**Issue by ceelsoin** [MoienTajik/AspNetCore-Developer-Roadmap#27]
When saving modified draw.io diagram my template resulting is complety diference of png saved in master branch.

Print screen: 
My export: http://prntscr.com/q1b5vj
Repository Export: http://prntscr.com/q1b64a

How to export with right template?

**Comment by MoienTajik** [comment]
Hi, actually we've migrated from Draw.io to [xMind Zen](https://www.xmind.net/download/).
I've changed the [CONTRIBUTING.MD](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap/blob/master/CONTRIBUTING.md) file accordingly.

**Comment by ceelsoin** [comment]
Thnx!
