### ISSUE TITLE
How to open the .xml?

### ISSUE THREAD

**Issue by imba-tjd** [MoienTajik/AspNetCore-Developer-Roadmap#29]
Hi. I'd like to update the zh-cn translation, but I don't know how to open the `aspnetcore-developer-roadmap.zh-Hans.xml`?

**Comment by imba-tjd** [comment]
Found this in the history of `CONTRIBUTING.md`

**Comment by MoienTajik** [comment]
Actually, we prefer to migrate the zh-Hans version to xMind too.

**Comment by imba-tjd** [comment]
I know. I need to find (and have found) the original translation.
