### ISSUE TITLE
Mixed indentation

### ISSUE THREAD

**Issue by imba-tjd** [MoienTajik/AspNetCore-Developer-Roadmap#31]
![图片](https://user-images.githubusercontent.com/24759802/70485137-0afa3400-1b29-11ea-9660-5217b87262ff.png)

Some of them are 3-spaces indented, but some others are 4-spaces indented.

**Comment by MoienTajik** [comment]
It would be good if we fix this and make all indentations integrated.

**Comment by JessicaBarclay** [comment]
PR https://github.com/MoienTajik/AspNetCore-Developer-Roadmap/pull/40
