### ISSUE TITLE
Compress your images automatically 

### ISSUE THREAD

**Issue by mjebrahimi** [MoienTajik/AspNetCore-Developer-Roadmap#41]
Use this Github Action that automatically compresses JPEGs, PNGs, and WebPs in Pull Requests.

https://github.com/calibreapp/image-actions

**Comment by MoienTajik** [comment]
Thanks! We're currently using [ImgBot](https://github.com/marketplace/imgbot) like [this pull-request](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap/pull/37).

Does this action give us any other advantages?

**Comment by mjebrahimi** [comment]
Very well.
I don't know the advantages of image-actions over this.
