### ISSUE TITLE
Prinable version with white backgorund

### ISSUE THREAD

**Issue by Arsikod** [MoienTajik/AspNetCore-Developer-Roadmap#43]
Hey man, great job on a roadmap.
Can you make a printable version with white backgorund?
Thanks.

**Comment by MoienTajik** [comment]
Printable version added: [Printable version](https://raw.githubusercontent.com/MoienTajik/AspNetCore-Developer-Roadmap/master/aspnetcore-developer-roadmap-printable.png)
