### ISSUE TITLE
It seems powersearchingwithgoogle is not accessible 

### ISSUE THREAD

**Issue by seasharpdeveloper** [MoienTajik/AspNetCore-Developer-Roadmap#45]
Please change powersearchingwithgoogle.com link to https://coursebuilder.withgoogle.com/
It seems it's not accessible anymore.

![image](https://user-images.githubusercontent.com/891361/82857431-f515db00-9ede-11ea-9f3f-5ded2cd09454.png)

**Comment by MoienTajik** [comment]
The URL seems ok: http://www.powersearchingwithgoogle.com/

**Comment by seasharpdeveloper** [comment]
ah it's redirected to https://www.codespaces.com/power-searching-with-google.html
