### ISSUE TITLE
Zh-Hans & Zh-Hant versions need to be updated according to the 2021 changes

### ISSUE THREAD

**Issue by MoienTajik** [MoienTajik/AspNetCore-Developer-Roadmap#51]
Zh-Hans & Zh-Hant versions need to be updated according to the 2021 changes

**Comment by kkbruce** [comment]
Give me some time and let me update to the 2021 version for Zh-Hant.

**Comment by kkbruce** [comment]
If you want, I can provide the zh-Hans 2021 version.

Also, remind that the users of these two Chinese language families are not the same:

* zh-Hans for China User.
* zh-Hant for Taiwan / Hong Kong User

So next time this can be divided into two issues to discuss.

**Comment by MoienTajik** [comment]
Thanks for the clarification! 
That would be great if you update the Zh-Hant version too. 😊

**Comment by kkbruce** [comment]
Ok, Give me some time and let me update to the 2021 version for Zh-Han**s**.

**Comment by kkbruce** [comment]
@MoienTajik 
I completed all zh-Hant, zh-Hans translation, and send PR, confirm it.

**Comment by MoienTajik** [comment]
Fixed by #63.
Thanks for your contribution!
