### ISSUE TITLE
Add Dapper to the list

### ISSUE THREAD

**Issue by dyako-baram** [MoienTajik/AspNetCore-Developer-Roadmap#56]
Dapper is a micro ORM which is alternative to Entity Framework core with better performance than EF

**Comment by anddrzejb** [comment]
On top of that, if that list suggests design patterns as CQRS, dapper (or similar) is IMHO a necessity for the queries. First of all EF in this case adds a significant overhead when creating entities which is not need (event with ```AsNoTracking()```). Also EF creates sometimes really baffling queries, when a bit more complex scenarios come into play. In such cases, ability to write custom queries is really useful and queries can run much faster with less resource drain..

**Comment by MoienTajik** [comment]
Added by 784eabe5e0ad5b31b994112f84725d9ec679d3fa
