### ISSUE TITLE
Consider adding Authentication & Authorization

### ISSUE THREAD

**Issue by anddrzejb** [MoienTajik/AspNetCore-Developer-Roadmap#57]
Authentication & authorization is a really huge part of AspNet Core, not mentioning that it is really important. I think it would be worth to add them. I would also suggest inclusion of OAuth and IDOpenConnect with IdentityServer4 implementation.

**Comment by MoienTajik** [comment]
Authentication & Authorization added to `ASP.NET Core Basics` section by 784eabe5e0ad5b31b994112f84725d9ec679d3fa
