### ISSUE TITLE
Auth and Identity

### ISSUE THREAD

**Issue by ardalis** [MoienTajik/AspNetCore-Developer-Roadmap#79]
Learning something about Auth, Identity, and Security probably deserves more of a mention than a bullet under ASP.NET Core. There's ASP.NET Identity, token vs. cookie auth, identity server, OIDC, SAML, other protocols, JWT tokens. I'd probably also include security and OWASP top 10 in the list somewhere as well.

**Comment by arminatwork** [comment]
> Learning something about Auth, Identity, and Security probably deserves more of a mention than a bullet under ASP.NET Core. There's ASP.NET Identity, token vs. cookie auth, identity server, OIDC, SAML, other protocols, JWT tokens. I'd probably also include security and OWASP top 10 in the list somewhere as well.

so there are in Asp.Net Core Basic section -> Authentication and Authorization

**Comment by ardalis** [comment]
@arminatwork yes and I'm saying this:

> probably deserves more of a mention than a bullet under ASP.NET Core.

**Comment by arminatwork** [comment]
> @arminatwork yes and I'm saying this:
> 
> > probably deserves more of a mention than a bullet under ASP.NET Core.

is cool
I suggest it topic; should have written more about it such as cookie and session
### note session , cookie and... is State Management!

**Comment by MoienTajik** [comment]
Added with more detail in 2022 version, thanks for your suggestion! ;)
