### ISSUE TITLE
Would Add debugging with WSL

### ISSUE THREAD

**Issue by KamranShahid** [MoienTajik/AspNetCore-Developer-Roadmap#84]
Would Add debugging with WSL as it quite beneficial

**Comment by MoienTajik** [comment]
How does it relate to ASP.NET Core?

**Comment by KamranShahid** [comment]
Sometime there are platform not supported exception where one thing supported in windows not work within linux. even i have face a scenario where one overload method of some thir party api not working in linux while working in windows. when i were able to debug via WSL i was able to reproduce problem and able to do sort of work arounds
