### ISSUE TITLE
Add subsections to the Design Patterns section

### ISSUE THREAD

**Issue by yaryrslv** [MoienTajik/AspNetCore-Developer-Roadmap#97]
Please add subsections to the Design Patterns section like:
(These are 21 classic GOF patterns)

**PATTERNS**
- Creational
_Abstract Factory
Builder
Factory Method
Object Pool
Prototype
Singleton_
- Structural
_Adapter
Bridge
Composite
Decorator
Facade
Flyweight
Private Class Data
Proxy_
- Behavioural
_Chain of responsibility
Command
Interpreter
Iterator
Mediator
Memento
Null Object
Observer
State
Strategy
Template method
Visitor_

**Comment by Aarnihauta** [comment]
And сoncurrency patterns

**Comment by MoienTajik** [comment]
It may not be necessary for all the design patterns to be specifically included on our roadmap. IMO, this would complicate the roadmap and make it noisy. Thoughts?

**Comment by samuelbarrionuevo** [comment]
of course, soo complicated much design patterns

**Comment by yaryrslv** [comment]
> It may not be necessary for all the design patterns to be specifically included on our roadmap. IMO, this would complicate the roadmap and make it noisy. Thoughts?

Maybe at least add a **GOF pattens** section, without subsections?
_(Seriously, this is extremely important for learning those architectural patterns that are already in the map)_
